"""Editorial source of truth: dated reporting plus original hypothetical tactics."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
SOURCES = [
    "https://efe.com/deportes/2026-09-30/cristiano-ronaldo-federacion-concentracion-seleccion/",
    "https://madeira.rtp.pt/desporto/jesus-fala-em-mal-entendido-e-diz-que-ronaldo-tem-as-portas-abertas/",
]

# None of the tactical diagrams represents measured player tracking or match footage.
SECTIONS = [
("Leaving camp is not retirement", "timeline", ["Departure confirmed", "Return still possible", "Role is the real question"],
"""Ronaldo left Portugal's camp. Now Jorge Jesus says the door is still open. So what actually happened, and does Portugal need Ronaldo starting every game? Let's separate what is confirmed from what is being assumed. Then let's look at the football: what changes with him up front, and what changes with a different kind of striker. Leaving a camp and retiring from international football are two different things. And saying a player can return does not tell you whether he starts. Those distinctions matter. Because the interesting question isn't who wins an argument on social media. It's what job Portugal needs its number nine to do."""),
("Two dates, two developments", "timeline", ["September 30: departure", "October 4: door open", "Checked October 5, 2026"],
"""Here is the short version of the reporting, checked on October fifth, twenty twenty-six. EFE reported on September thirtieth that the Portuguese federation confirmed Ronaldo had left the camp in Copenhagen. The federation did not give a full explanation for his departure. His message, as reported, did not announce a permanent international retirement. Then, on October fourth, RTP reported Jorge Jesus saying a return remained possible and describing the situation as a misunderstanding. That is the verified timeline for this video. It gives us a departure and an invitation to return. It does not give us a confirmed return date or a guaranteed place in the starting eleven."""),
("Don't fill the gaps with guesses", "decision", ["Confirmed event", "Unanswered questions", "Analysis is not inside information"],
"""When a story has a gap, the tempting move is to fill it with the most dramatic explanation. A secret feud. A final goodbye. Someone winning a power struggle. But a compelling explanation still needs evidence. We don't have a complete account of every private conversation, so I'm not going to pretend we do. The coach's public position tells us something about the possibility of a return. It doesn't settle every detail of what happened before the departure. Keep those questions separate. What happened behind the scenes is a reporting question. How you would use a striker is a football question. We can discuss the second without inventing an answer to the first."""),
("Choose a job before a name", "decision", ["Opponent", "Chance creation", "Team responsibilities"],
"""So let's set the headline aside for a minute. Imagine you're choosing a Portugal team for a specific opponent. Before you write the striker's name, write down three things. Where will your chances come from? Where does the opponent leave space? And what must the striker do when your team loses the ball? Those questions stop the debate becoming a vote on someone's career. A striker can be useful in one game plan and awkward in another. That isn't a contradiction. It is a selection decision. The pitch on screen is an original illustration, not tracking data from a real match. We'll use it to make the tradeoffs visible rather than claim the drawing proves them."""),
("First problem: owning the box", "box", ["Occupy a defender", "Attack the delivery", "Create a finishing option"],
"""Start with a compact defense. Your winger has the ball near the edge of the penalty area. A central striker standing between the defenders gives that winger an obvious finishing target. But the target only helps if the delivery reaches a useful area. A cross into a crowded box isn't automatically a good chance. The striker needs to separate at the right moment, and the passer needs time to look up. In this illustration, the yellow line shows a possible delivery, not a guaranteed goal. Notice how the striker's position changes the defender's attention. That can create room for someone else, even when the striker never touches the ball. The value isn't limited to the final shot."""),
("The pass before the finish", "space", ["Free the wide player", "Create time to look up", "Then attack the box"],
"""Now work backward from that cross. How did the winger get enough time to deliver it? Perhaps a midfielder drew an opponent inward. Perhaps an overlapping runner pulled a second defender away. Without those earlier actions, the ball carrier can get trapped and the striker waits for a pass that never arrives. This is why counting a forward's chances without looking at the supply can mislead you. The team may have failed to create the situation its striker needs. If your plan depends on penalty area finishing, your buildup must actually feed the penalty area. Otherwise you've picked a specialist and then given him a different job. Watch the space outside the box, not just the player inside it."""),
("Against a low block", "box", ["Width stretches the defense", "Cutback offers another route", "Don't cross by default"],
"""Against an opponent sitting deep, space behind the back line may barely exist. The useful space can be beside the block or just behind its midfield. That suggests several routes: combine on the wing, reach the byline, or find a cutback instead of lifting every ball into the air. A central forward can hold the defenders while a late runner attacks the cutback zone. But if everyone stands waiting in the same area, Portugal becomes easier to defend. One player must pin, another must move, and the passer must recognize the opening. The point is not that Ronaldo must start against every low block. The point is that a box-focused role needs coordinated movement around it."""),
("Second problem: the first press", "press", ["Close one passing lane", "Midfield moves with the striker", "Pressing is a team action"],
"""Now switch the scene. The opponent is building from the back, and Portugal wants to win the ball higher up. The striker's run matters, but running straight at the ball isn't a whole pressing system. The angle of that run can discourage one pass and invite another. Then the winger or midfielder must react to the pass you've encouraged. If those players arrive late, the opponent simply plays through the gap. In this diagram, look at the distance between the first forward and the midfield. A spectacular sprint doesn't fix a disconnected team. The fair question is whether the selected striker can perform the agreed pressing job, and whether the players behind him support it."""),
("Different movement, different spaces", "space", ["Drop to connect", "Someone must run beyond", "Movement has a cost"],
"""A more mobile forward might drop into midfield or drift into a channel. That can give the ball carrier another passing option. It can also pull a center back into an uncomfortable decision: follow the forward, or hold the line? But movement has a cost. If the striker leaves the middle and nobody attacks it, a promising cross can find an empty area. That's why saying a forward moves more doesn't finish the argument. What happens after he moves? A winger may need to run beyond him. A midfielder may need to arrive in the box. A change at number nine can require changes everywhere else. You don't get the benefit just by swapping one name on the team sheet."""),
("Comparison one: keep the same supply", "box", ["Same wide starting point", "Different striker position", "Who reaches the delivery?"],
"""Let's compare two hypothetical attacks from the same wide starting point. In the first, the striker stays close to the center backs. The winger has a target in the box and a midfielder arrives behind the play. In the second, the striker drops toward the ball. Now the winger may have a short passing option, but somebody else has to occupy the defenders. Neither picture is automatically better. If the winger has a clear crossing lane, the first may make sense. If the winger is trapped and needs help, the second may offer a way out. This isn't a video game experiment or a replay from Portugal. It is a simple illustration of how one movement changes the next decision."""),
("Comparison two: the ball is lost", "press", ["Who pressures the ball?", "Who protects the center?", "Who tracks the runner?"],
"""Now stop the attack at the least glamorous moment: the ball is lost. Who pressures the new ball carrier? Who blocks the central pass? Who protects the space behind the attacking players? These responsibilities exist whether the striker is Ronaldo or someone else. If your forwards stay high, you may preserve a dangerous counterattacking outlet, but your midfield can have more ground to cover. If the forward drops, you may gain another body near the ball, but lose an immediate target up front. Again, this is a tradeoff, not a verdict. A coach should decide which risk the team can manage. The worst setup is one where different players think different people are responsible for the same space."""),
("A substitute can change the question", "decision", ["What has the opponent shown?", "What does the score require?", "Choose the next role"],
"""There is a third option that the start-or-bench argument often hides: change the role during the match. A substitute doesn't enter the game that existed before kickoff. He enters the situation that exists now. Maybe the opponent is defending deeper. Maybe Portugal needs more penalty area presence. Maybe the team has a lead and needs a different way to keep possession. The substitution should answer that situation. Calling any substitute appearance an insult misses the tactical reason it might be useful. Equally, bringing on a famous player without explaining the job is not a plan. Ask what has changed on the pitch, and what the incoming player adds that the current setup is missing."""),
("What would actually count as evidence?", "decision", ["Quality of the chances", "Repeatable patterns", "Comparable match situations"],
"""If we want to move beyond opinion, we need more than a final score or a single highlight. Look for repeated patterns. Does the team consistently create cleaner shots? Can it keep the opponent from escaping pressure? Does the striker's movement help teammates reach useful positions? And compare situations that are actually comparable. Playing a deep defense while chasing a goal is different from protecting a lead against a team that commits players forward. A result can support a question without answering every part of it. I am not putting made-up percentages on this diagram. We don't have a controlled dataset in this video. What we have is a framework for watching the next match with better questions."""),
("Why a game simulation isn't proof", "space", ["Useful for visualizing", "Controlled settings matter", "Real football stays different"],
"""If you enjoy football gaming, you can explore these ideas in your own matches. Keep the opponent, formation, difficulty and other settings consistent, then compare where your chances come from. But be careful about what the exercise tells you. A game engine has its own movement rules, player attributes and opponent behavior. It can help you visualize a tactical problem, but it cannot predict a real international match. One spectacular goal is not a controlled comparison either. For this episode, the graphics are original tactical animations. No gameplay test has been presented as evidence. A future gaming episode can show an actual recorded experiment, with its limitations visible, rather than turn a simulation into a claim about real players."""),
("The decision should survive the headline", "decision", ["Define the role", "Assess the match", "Explain the tradeoff"],
"""Here's my position. Start with the opponent and the job. Then select the player who best fits the job, including the responsibilities around him. That might lead you to Ronaldo in one plan and another forward in a different plan. It might lead you to a substitution rather than a permanent rule. Fans can disagree with those decisions, and that is part of football. But a useful disagreement explains the tradeoff. Are you prioritizing penalty area presence? A passing connection? A pressing trigger? Say which one and why. 'He is a legend' describes a career. 'He must never start' is another blanket statement. Neither tells the winger where to pass or the midfielder where to move."""),
("Keep the story and the tactics separate", "timeline", ["Departure is a reported fact", "Return is a possibility", "Selection remains a football decision"],
"""Bring that back to the news. The reported departure tells us that Ronaldo left this camp. The coach's later comments tell us he has not publicly closed the door to a return. They don't give us a full account of the private discussions, and they don't settle a future lineup. If new reporting changes the timeline, the news needs updating. The tactical questions will still be useful: what does Portugal need from its striker, and what does the rest of the team need to do around him? That's why this discussion can be more than a reaction to a dramatic headline. It gives you a way to assess the football once the next team is actually named."""),
("Your call: name the opponent and the role", "decision", ["Choose an opponent", "Choose the striker's job", "Give a football reason"],
"""So my take is simple: pick the striker for the match plan, then explain how the whole team supports that choice. Don't treat a camp departure as a retirement announcement, and don't treat an open door as a promise of automatic starts. Now your turn. Which type of opponent would make you start Ronaldo, and which would make you change the setup? Give me the football reason: the space you want to attack, the chance you want to create, or the passing lane you want to close. The source links and chapter list are in the description if you want to check the reporting or revisit a comparison. That's the debate worth having."""),
]

SHORTS = [
    ("Leaving Camp Isn't Retirement", "timeline", ["Departure is not retirement", "A return remains possible"],
     "Did Ronaldo leaving Portugal's camp mean he retired from international football? That's not what the confirmed information says. The federation confirmed his departure. Then Jorge Jesus said the door was still open. Those are two different developments. The bigger question is what role Ronaldo would return to. I've broken down the timeline and the football in the full video. Tap the related video below my channel name."),
    ("Should Ronaldo Start Every Game?", "decision", ["Name the opponent", "Then choose the role"],
     "Should Ronaldo start every Portugal game? I'd ask a different question: what does this opponent force Portugal to do? You might want a striker attacking crosses and owning the penalty area. In another match, you might need different movement or pressing. Saying start him or bench him skips the actual football. In the full video, I compare both setups. Tap the related video below my channel name and see which one you'd choose."),
    ("One Striker Run Changes the Whole Attack", "space", ["Striker drops deeper", "Who attacks the empty space?"],
     "Watch what happens when the striker drops toward the ball. The winger gains a passing option, but someone else has to attack the penalty area. More movement isn't automatically better. It changes everybody else's job. This is a tactical illustration, not match footage or a gameplay test. In the full video, I compare the spaces a central striker and a roaming forward create. Tap the related video below my channel name for the full breakdown."),
]


def write(name, title, sections, vertical=False):
    description = "Original football analysis with tactical illustrations and synthetic English narration. Facts checked October 5, 2026; future developments may change the news. No match footage or simulated results are presented as evidence.\n\nSources:\n" + "\n".join(SOURCES)
    plan = {"metadata": {"title": title, "description": description,
                          "hashtags": ["#Ronaldo", "#Portugal", "#Football"]},
            "vertical": vertical, "voice": "en-US-GuyNeural", "checked_on": "2026-10-05",
            "sources": SOURCES, "scenes": [dict(heading=h, mode=m, points=p, narration=n) for h,m,p,n in sections]}
    (ROOT / name).write_text(json.dumps(plan, indent=2), encoding="utf-8")


if __name__ == "__main__":
    write("main.json", "Ronaldo Left Portugal. So Why Is the Door Still Open?", SECTIONS)
    for index, section in enumerate(SHORTS, 1):
        write(f"short-{index}.json", section[0], [section], True)
    print(f"Main narration: {sum(len(s[3].split()) for s in SECTIONS)} words")
